version: '3.8'
services:
  mysql-db:
    image: mysql:8.0.46
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_cv_db
    ports:
      - "3306:3306"
  api-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/api_cv_db?allowPublicKeyRetrieval=true&useSSL=false